(cl:defpackage rmus_solution-srv
  (:use )
  (:export
   "GRASPSIGNAL"
   "<GRASPSIGNAL-REQUEST>"
   "GRASPSIGNAL-REQUEST"
   "<GRASPSIGNAL-RESPONSE>"
   "GRASPSIGNAL-RESPONSE"
   "SETGOAL"
   "<SETGOAL-REQUEST>"
   "SETGOAL-REQUEST"
   "<SETGOAL-RESPONSE>"
   "SETGOAL-RESPONSE"
   "SWITCH"
   "<SWITCH-REQUEST>"
   "SWITCH-REQUEST"
   "<SWITCH-RESPONSE>"
   "SWITCH-RESPONSE"
  ))

