// Generated by gencpp from file rmus_solution/graspsignalResponse.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_GRASPSIGNALRESPONSE_H
#define RMUS_SOLUTION_MESSAGE_GRASPSIGNALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmus_solution
{
template <class ContainerAllocator>
struct graspsignalResponse_
{
  typedef graspsignalResponse_<ContainerAllocator> Type;

  graspsignalResponse_()
    : res(false)
    , response()  {
    }
  graspsignalResponse_(const ContainerAllocator& _alloc)
    : res(false)
    , response(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::rmus_solution::graspsignalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmus_solution::graspsignalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct graspsignalResponse_

typedef ::rmus_solution::graspsignalResponse_<std::allocator<void> > graspsignalResponse;

typedef boost::shared_ptr< ::rmus_solution::graspsignalResponse > graspsignalResponsePtr;
typedef boost::shared_ptr< ::rmus_solution::graspsignalResponse const> graspsignalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmus_solution::graspsignalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmus_solution::graspsignalResponse_<ContainerAllocator1> & lhs, const ::rmus_solution::graspsignalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmus_solution::graspsignalResponse_<ContainerAllocator1> & lhs, const ::rmus_solution::graspsignalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmus_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::graspsignalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::graspsignalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::graspsignalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c684d66cac50a24a80edabfe629efad";
  }

  static const char* value(const ::rmus_solution::graspsignalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c684d66cac50a24ULL;
  static const uint64_t static_value2 = 0xa80edabfe629efadULL;
};

template<class ContainerAllocator>
struct DataType< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmus_solution/graspsignalResponse";
  }

  static const char* value(const ::rmus_solution::graspsignalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n"
"string response\n"
;
  }

  static const char* value(const ::rmus_solution::graspsignalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct graspsignalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmus_solution::graspsignalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmus_solution::graspsignalResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_GRASPSIGNALRESPONSE_H
