// Generated by gencpp from file rmus_solution/graspsignal.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_GRASPSIGNAL_H
#define RMUS_SOLUTION_MESSAGE_GRASPSIGNAL_H

#include <ros/service_traits.h>


#include <rmus_solution/graspsignalRequest.h>
#include <rmus_solution/graspsignalResponse.h>


namespace rmus_solution
{

struct graspsignal
{

typedef graspsignalRequest Request;
typedef graspsignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct graspsignal
} // namespace rmus_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmus_solution::graspsignal > {
  static const char* value()
  {
    return "ba5c545fc7cb2bb25e9f962a2a65350e";
  }

  static const char* value(const ::rmus_solution::graspsignal&) { return value(); }
};

template<>
struct DataType< ::rmus_solution::graspsignal > {
  static const char* value()
  {
    return "rmus_solution/graspsignal";
  }

  static const char* value(const ::rmus_solution::graspsignal&) { return value(); }
};


// service_traits::MD5Sum< ::rmus_solution::graspsignalRequest> should match
// service_traits::MD5Sum< ::rmus_solution::graspsignal >
template<>
struct MD5Sum< ::rmus_solution::graspsignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::graspsignal >::value();
  }
  static const char* value(const ::rmus_solution::graspsignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::graspsignalRequest> should match
// service_traits::DataType< ::rmus_solution::graspsignal >
template<>
struct DataType< ::rmus_solution::graspsignalRequest>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::graspsignal >::value();
  }
  static const char* value(const ::rmus_solution::graspsignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmus_solution::graspsignalResponse> should match
// service_traits::MD5Sum< ::rmus_solution::graspsignal >
template<>
struct MD5Sum< ::rmus_solution::graspsignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::graspsignal >::value();
  }
  static const char* value(const ::rmus_solution::graspsignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::graspsignalResponse> should match
// service_traits::DataType< ::rmus_solution::graspsignal >
template<>
struct DataType< ::rmus_solution::graspsignalResponse>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::graspsignal >::value();
  }
  static const char* value(const ::rmus_solution::graspsignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_GRASPSIGNAL_H
