// Generated by gencpp from file rmus_solution/setgoalRequest.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_SETGOALREQUEST_H
#define RMUS_SOLUTION_MESSAGE_SETGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmus_solution
{
template <class ContainerAllocator>
struct setgoalRequest_
{
  typedef setgoalRequest_<ContainerAllocator> Type;

  setgoalRequest_()
    : point(0)
    , call()  {
    }
  setgoalRequest_(const ContainerAllocator& _alloc)
    : point(0)
    , call(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _point_type;
  _point_type point;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _call_type;
  _call_type call;





  typedef boost::shared_ptr< ::rmus_solution::setgoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmus_solution::setgoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setgoalRequest_

typedef ::rmus_solution::setgoalRequest_<std::allocator<void> > setgoalRequest;

typedef boost::shared_ptr< ::rmus_solution::setgoalRequest > setgoalRequestPtr;
typedef boost::shared_ptr< ::rmus_solution::setgoalRequest const> setgoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmus_solution::setgoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmus_solution::setgoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmus_solution::setgoalRequest_<ContainerAllocator1> & lhs, const ::rmus_solution::setgoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point &&
    lhs.call == rhs.call;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmus_solution::setgoalRequest_<ContainerAllocator1> & lhs, const ::rmus_solution::setgoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmus_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::setgoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::setgoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::setgoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a358ca69337c562fa080694379731528";
  }

  static const char* value(const ::rmus_solution::setgoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa358ca69337c562fULL;
  static const uint64_t static_value2 = 0xa080694379731528ULL;
};

template<class ContainerAllocator>
struct DataType< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmus_solution/setgoalRequest";
  }

  static const char* value(const ::rmus_solution::setgoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 point\n"
"string call\n"
;
  }

  static const char* value(const ::rmus_solution::setgoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.call);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setgoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmus_solution::setgoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmus_solution::setgoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    Printer<int32_t>::stream(s, indent + "  ", v.point);
    s << indent << "call: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.call);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_SETGOALREQUEST_H
