// Generated by gencpp from file rmus_solution/setgoal.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_SETGOAL_H
#define RMUS_SOLUTION_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <rmus_solution/setgoalRequest.h>
#include <rmus_solution/setgoalResponse.h>


namespace rmus_solution
{

struct setgoal
{

typedef setgoalRequest Request;
typedef setgoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setgoal
} // namespace rmus_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmus_solution::setgoal > {
  static const char* value()
  {
    return "5dd6c60142d9c86b4dfc9ca1994ff38a";
  }

  static const char* value(const ::rmus_solution::setgoal&) { return value(); }
};

template<>
struct DataType< ::rmus_solution::setgoal > {
  static const char* value()
  {
    return "rmus_solution/setgoal";
  }

  static const char* value(const ::rmus_solution::setgoal&) { return value(); }
};


// service_traits::MD5Sum< ::rmus_solution::setgoalRequest> should match
// service_traits::MD5Sum< ::rmus_solution::setgoal >
template<>
struct MD5Sum< ::rmus_solution::setgoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::setgoal >::value();
  }
  static const char* value(const ::rmus_solution::setgoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::setgoalRequest> should match
// service_traits::DataType< ::rmus_solution::setgoal >
template<>
struct DataType< ::rmus_solution::setgoalRequest>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::setgoal >::value();
  }
  static const char* value(const ::rmus_solution::setgoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmus_solution::setgoalResponse> should match
// service_traits::MD5Sum< ::rmus_solution::setgoal >
template<>
struct MD5Sum< ::rmus_solution::setgoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::setgoal >::value();
  }
  static const char* value(const ::rmus_solution::setgoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::setgoalResponse> should match
// service_traits::DataType< ::rmus_solution::setgoal >
template<>
struct DataType< ::rmus_solution::setgoalResponse>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::setgoal >::value();
  }
  static const char* value(const ::rmus_solution::setgoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_SETGOAL_H
