// Generated by gencpp from file rmus_solution/switchResponse.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_SWITCHRESPONSE_H
#define RMUS_SOLUTION_MESSAGE_SWITCHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmus_solution
{
template <class ContainerAllocator>
struct switchResponse_
{
  typedef switchResponse_<ContainerAllocator> Type;

  switchResponse_()
    : success(0)  {
    }
  switchResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rmus_solution::switchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmus_solution::switchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct switchResponse_

typedef ::rmus_solution::switchResponse_<std::allocator<void> > switchResponse;

typedef boost::shared_ptr< ::rmus_solution::switchResponse > switchResponsePtr;
typedef boost::shared_ptr< ::rmus_solution::switchResponse const> switchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmus_solution::switchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmus_solution::switchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmus_solution::switchResponse_<ContainerAllocator1> & lhs, const ::rmus_solution::switchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmus_solution::switchResponse_<ContainerAllocator1> & lhs, const ::rmus_solution::switchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmus_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::switchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::switchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::switchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::switchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::switchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::switchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmus_solution::switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cca7c80398b8b31af04b80534923f16";
  }

  static const char* value(const ::rmus_solution::switchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cca7c80398b8b31ULL;
  static const uint64_t static_value2 = 0xaf04b80534923f16ULL;
};

template<class ContainerAllocator>
struct DataType< ::rmus_solution::switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmus_solution/switchResponse";
  }

  static const char* value(const ::rmus_solution::switchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmus_solution::switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 success\n"
;
  }

  static const char* value(const ::rmus_solution::switchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmus_solution::switchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct switchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmus_solution::switchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmus_solution::switchResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_SWITCHRESPONSE_H
