// Generated by gencpp from file rmus_solution/switchRequest.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_SWITCHREQUEST_H
#define RMUS_SOLUTION_MESSAGE_SWITCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmus_solution
{
template <class ContainerAllocator>
struct switchRequest_
{
  typedef switchRequest_<ContainerAllocator> Type;

  switchRequest_()
    : mode(0)  {
    }
  switchRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::rmus_solution::switchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmus_solution::switchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct switchRequest_

typedef ::rmus_solution::switchRequest_<std::allocator<void> > switchRequest;

typedef boost::shared_ptr< ::rmus_solution::switchRequest > switchRequestPtr;
typedef boost::shared_ptr< ::rmus_solution::switchRequest const> switchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmus_solution::switchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmus_solution::switchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmus_solution::switchRequest_<ContainerAllocator1> & lhs, const ::rmus_solution::switchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmus_solution::switchRequest_<ContainerAllocator1> & lhs, const ::rmus_solution::switchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmus_solution

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmus_solution::switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmus_solution::switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::switchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmus_solution::switchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmus_solution::switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::rmus_solution::switchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::rmus_solution::switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmus_solution/switchRequest";
  }

  static const char* value(const ::rmus_solution::switchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmus_solution::switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
;
  }

  static const char* value(const ::rmus_solution::switchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmus_solution::switchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct switchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmus_solution::switchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmus_solution::switchRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_SWITCHREQUEST_H
