// Generated by gencpp from file rmus_solution/switch.msg
// DO NOT EDIT!


#ifndef RMUS_SOLUTION_MESSAGE_SWITCH_H
#define RMUS_SOLUTION_MESSAGE_SWITCH_H

#include <ros/service_traits.h>


#include <rmus_solution/switchRequest.h>
#include <rmus_solution/switchResponse.h>


namespace rmus_solution
{

struct switch
{

typedef switchRequest Request;
typedef switchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct switch
} // namespace rmus_solution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmus_solution::switch > {
  static const char* value()
  {
    return "9ae8834e0ab84ed7c29d5f2c87a2b979";
  }

  static const char* value(const ::rmus_solution::switch&) { return value(); }
};

template<>
struct DataType< ::rmus_solution::switch > {
  static const char* value()
  {
    return "rmus_solution/switch";
  }

  static const char* value(const ::rmus_solution::switch&) { return value(); }
};


// service_traits::MD5Sum< ::rmus_solution::switchRequest> should match
// service_traits::MD5Sum< ::rmus_solution::switch >
template<>
struct MD5Sum< ::rmus_solution::switchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::switch >::value();
  }
  static const char* value(const ::rmus_solution::switchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::switchRequest> should match
// service_traits::DataType< ::rmus_solution::switch >
template<>
struct DataType< ::rmus_solution::switchRequest>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::switch >::value();
  }
  static const char* value(const ::rmus_solution::switchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmus_solution::switchResponse> should match
// service_traits::MD5Sum< ::rmus_solution::switch >
template<>
struct MD5Sum< ::rmus_solution::switchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmus_solution::switch >::value();
  }
  static const char* value(const ::rmus_solution::switchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmus_solution::switchResponse> should match
// service_traits::DataType< ::rmus_solution::switch >
template<>
struct DataType< ::rmus_solution::switchResponse>
{
  static const char* value()
  {
    return DataType< ::rmus_solution::switch >::value();
  }
  static const char* value(const ::rmus_solution::switchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMUS_SOLUTION_MESSAGE_SWITCH_H
